project:
  name: 'ijcai'
  version: 1.0
  state: 'ada_src_pa_erda_05_lambda'
  stage: 'exp'


hwconfig:
  num_cuda: 0
  num_workers: 8

model:
  in_feat_size: 1
  out_classes: 19
  pretrained: /data4/vaibhav/musmix/output/model_checkpoints/cvpr/1.0/tr_src/tr_src_ep_9_tridx_4499.ckpt

datasets:
  source1_name: 'SynLiDAR'
  source1_mapping_path: '_resources/synlidar_semantickitti.yaml'
  source1_path: '/data3/vaibhav/SynLiDAR/sequences'
  source1_weights: None
  source2_name: 'SemanticPOSS'
  source2_path: '/data4/vaibhav/lidardata/SemanticPOSS_dataset/dataset/sequences'
  source2_weights: None
  target_name: 'SemanticKITTI'
  target_path: "/data4/vaibhav/lidardata/semantic_kitti/sequences/"
  voxel_size: 0.05
  sub_num: 150000
  version: 'full'
  ignore_label: -1
  num_classes: 19
  augment_data: True
  augment_mask_data: True
  s2s1_wt: 0.5
  s1s2_wt: 0.5

mask_fn:
  select_ratio: 0.5
  save_mixing: False
  threshold: 0.9
  save_dir: '/data4/vaibhav/musmix/output/vis_mix/'

dataloaders:
  batch_size: 4
  shuffle: False
  pin_memory: True

pipelines:
  seed: 42
  epochs: 10
  optim_lr: 0.001
  betas: (0.99, 999)
  model_checkpoint: '/data4/vaibhav/musmix/output/model_checkpoints/'
  lambda_erda: 0.5

results:
  csv_save_dir: '/data4/vaibhav/musmix/output/results'
  chk_save_dir: '/data4/vaibhav/musmix/output/model_checkpoints'

